/**
 * Zod mirror of normalized-record.schema.json.
 *
 * The SourceType enum below is GENERATED from the canonical schema. All three
 * files are siblings in this same directory (packages/contracts/):
 *   - normalized-record.schema.json   (source of truth)
 *   - normalizedRecord.ts             (this file)
 *   - normalized_record.py            (Pydantic mirror)
 *
 * Do not add a source_type by hand here. Add it to the canonical schema and
 * run `python3 scripts/sync_contracts.py --write`; CI runs `--check` and
 * fails on drift.
 */

import { z } from "zod";

export const SourceType = z.enum([
  // SOURCE_TYPE GENERATED FROM packages/contracts/normalized-record.schema.json
  // generated by scripts/sync_contracts.py -- do not edit by hand; add new values to the canonical schema and re-run with --write
  "crash_report",
  "siri_feedback",
  "sfa_analytics",
  "xp_amp_telemetry",
  "safari_history",
  "sms_attachment",
  "network_usage",
  "gcloud_log",
  "syslog_line",
  "mvt_ioc_detection",
  "timestamp_anomaly",
  "ileapp_record",
  "llm_flagged_anomaly",
  // END SOURCE_TYPE
]);

export type SourceType = z.infer<typeof SourceType>;

export const NormalizedRecord = z
  .object({
    incident_id: z.string().nullable().optional().default(null),
    source_type: SourceType,
    event_time: z.string().datetime().nullable().optional().default(null),
    bug_type: z.string().nullable().optional().default(null),
    process_name: z.string().nullable().optional().default(null),
    pid: z.number().int().nullable().optional().default(null),
    bundle_id: z.string().nullable().optional().default(null),
    fields: z.record(z.string(), z.unknown()).default({}),
  })
  .strict();

export type NormalizedRecord = z.infer<typeof NormalizedRecord>;
