"use strict";
/**
 * Zod mirror of normalized-record.schema.json.
 *
 * The SourceType enum below is GENERATED from the canonical schema. All three
 * files are siblings in this same directory (packages/contracts/):
 *   - normalized-record.schema.json   (source of truth)
 *   - normalizedRecord.ts             (this file)
 *   - normalized_record.py            (Pydantic mirror)
 *
 * Do not add a source_type by hand here. Add it to the canonical schema and
 * run `python3 scripts/sync_contracts.py --write`; CI runs `--check` and
 * fails on drift.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NormalizedRecord = exports.SourceType = void 0;
const zod_1 = require("zod");
exports.SourceType = zod_1.z.enum([
    // SOURCE_TYPE GENERATED FROM packages/contracts/normalized-record.schema.json
    // generated by scripts/sync_contracts.py -- do not edit by hand; add new values to the canonical schema and re-run with --write
    "crash_report",
    "siri_feedback",
    "sfa_analytics",
    "xp_amp_telemetry",
    "safari_history",
    "sms_attachment",
    "network_usage",
    "gcloud_log",
    "syslog_line",
    "mvt_ioc_detection",
    "timestamp_anomaly",
    "ileapp_record",
    // END SOURCE_TYPE
]);
exports.NormalizedRecord = zod_1.z
    .object({
    incident_id: zod_1.z.string().nullable().optional().default(null),
    source_type: exports.SourceType,
    event_time: zod_1.z.string().datetime().nullable().optional().default(null),
    bug_type: zod_1.z.string().nullable().optional().default(null),
    process_name: zod_1.z.string().nullable().optional().default(null),
    pid: zod_1.z.number().int().nullable().optional().default(null),
    bundle_id: zod_1.z.string().nullable().optional().default(null),
    fields: zod_1.z.record(zod_1.z.string(), zod_1.z.unknown()).default({}),
})
    .strict();
