auth_enabled: false
server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days default

chunk_target_size: 1048576

# Default: local-only file storage. For centralization, mount S3 credentials and
# change object_store to s3 and configure the buckets accordingly.
