"""
Pydantic mirror of normalized-record.schema.json.

Every Python extractor imports NormalizedRecord from here and constructs one
per source record before writing to Postgres. This is what makes a new
extractor "additive" instead of risky -- it can't drift from the shared
envelope because the type checker/validator enforces it at construction time,
not at report-render time.

The SourceType enum below is GENERATED from the canonical schema. All three
files are siblings in this same directory (packages/contracts/):
  - normalized-record.schema.json   (source of truth)
  - normalizedRecord.ts             (TypeScript/Zod mirror)
  - normalized_record.py            (this file)

Do not add a source_type by hand here. Add it to the canonical schema and run
`python3 scripts/sync_contracts.py --write`; CI runs `--check` and fails on
drift.

The model fields are still hand-written, because their type expressions are
genuinely language-specific and read better than codegen would make them. The
sync script asserts the field *names* match the schema even though it does not
generate them.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict


class SourceType(str, Enum):
    """Registration point for extractors.

    Notes on individual values that need them, kept here rather than inline in
    the generated block below (which is overwritten):

    mvt_ioc_detection
        The mvt_iocs extractor consumes mvt-ios's own JSON/CSV output directly
        instead of re-deriving from a raw DB, unlike safari/sms/network. See
        its README for the "these are already analysis output, not raw
        evidence" rationale.

    ileapp_record
        Records bridged from iLEAPP. One iLEAPP artifact can be a CSV, a TSV,
        or a table inside a SQLite export, so `fields.source_artifact` carries
        the artifact (and table) name.
    """

    # SOURCE_TYPE GENERATED FROM packages/contracts/normalized-record.schema.json
    # generated by scripts/sync_contracts.py -- do not edit by hand; add new values to the canonical schema and re-run with --write
    CRASH_REPORT = "crash_report"
    SIRI_FEEDBACK = "siri_feedback"
    SFA_ANALYTICS = "sfa_analytics"
    XP_AMP_TELEMETRY = "xp_amp_telemetry"
    SAFARI_HISTORY = "safari_history"
    SMS_ATTACHMENT = "sms_attachment"
    NETWORK_USAGE = "network_usage"
    GCLOUD_LOG = "gcloud_log"
    SYSLOG_LINE = "syslog_line"
    MVT_IOC_DETECTION = "mvt_ioc_detection"
    TIMESTAMP_ANOMALY = "timestamp_anomaly"
    ILEAPP_RECORD = "ileapp_record"
    # END SOURCE_TYPE


class NormalizedRecord(BaseModel):
    model_config = ConfigDict(extra="forbid")

    incident_id: str | None = None
    source_type: SourceType
    event_time: datetime | None = None
    bug_type: str | None = None
    process_name: str | None = None
    pid: int | None = None
    bundle_id: str | None = None
    fields: dict[str, Any] = {}
