#!/usr/bin/env python3
"""
Generate the language mirrors of the canonical normalized-record contract.

    python3 scripts/sync_contracts.py --check    # exit 1 on drift (CI)
    python3 scripts/sync_contracts.py --write    # regenerate the mirrors

Why this exists
---------------
packages/contracts/normalized-record.schema.json is the declared source of
truth, and both mirrors carried a comment instructing contributors to "keep
this in lockstep" and to "change all three in the same commit". They did not
stay in lockstep. The canonical schema's `source_type` enum was missing
`ileapp_record` while both mirrors declared it, so every record the iLEAPP
extractor produced validated fine against the Pydantic and Zod models and was
rejected by the JSON schema the adapter actually loads. The failure surfaced as
a validation error attributable to no single file, on the one path least likely
to be exercised locally.

A comment asking three files to agree is a convention. Conventions lose to
copy-paste under deadline. The enum is the one part of the contract that is
purely declarative -- a list of strings, no prose, no language-specific
idiom -- so it can simply be generated, and then agreement is not something
anyone has to remember.

What is generated vs. checked
-----------------------------
GENERATED: the `source_type` enum members in each mirror, between explicit
BEGIN/END markers. Everything outside the markers -- the docstrings explaining
*why* each value exists, the Pydantic/Zod model bodies -- is hand-written and
left untouched, because that prose is worth more than the uniformity codegen
would impose on it.

CHECKED: the top-level property names in each mirror against the schema's.
Fields are not generated because their type expressions are genuinely
language-specific (`datetime | None` vs `z.string().datetime().nullable()`),
and generating them would mean either a type mapper that guesses or mirrors
that read worse than the ones a human wrote. A missing or extra *field* is
still drift, though, so it is asserted rather than ignored.

Layout
------
All three files are siblings under packages/contracts/:
    packages/contracts/normalized-record.schema.json   (source of truth)
    packages/contracts/normalized_record.py             (Pydantic mirror)
    packages/contracts/normalizedRecord.ts               (Zod mirror)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACTS_DIR = REPO_ROOT / "packages" / "contracts"
SCHEMA_PATH = CONTRACTS_DIR / "normalized-record.schema.json"
PYDANTIC_PATH = CONTRACTS_DIR / "normalized_record.py"
ZOD_PATH = CONTRACTS_DIR / "normalizedRecord.ts"

BEGIN = "SOURCE_TYPE GENERATED FROM packages/contracts/normalized-record.schema.json"
END = "END SOURCE_TYPE"

_GENERATED_NOTE = (
    "generated by scripts/sync_contracts.py -- do not edit by hand; "
    "add new values to the canonical schema and re-run with --write"
)


class DriftError(Exception):
    """A mirror disagrees with the canonical schema."""


# ---------------------------------------------------------------------------
# Canonical schema
# ---------------------------------------------------------------------------


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def source_types(schema: dict) -> list[str]:
    values = schema["properties"]["source_type"]["enum"]
    if not values:
        raise DriftError("canonical schema declares an empty source_type enum")
    duplicates = {value for value in values if values.count(value) > 1}
    if duplicates:
        raise DriftError(f"canonical schema has duplicate source_type values: {sorted(duplicates)}")
    return list(values)


def schema_properties(schema: dict) -> set[str]:
    return set(schema["properties"])


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render_pydantic_enum(values: list[str]) -> str:
    lines = [f"    # {_GENERATED_NOTE}"]
    for value in values:
        lines.append(f'    {value.upper()} = "{value}"')
    return "\n".join(lines)


def render_zod_enum(values: list[str]) -> str:
    lines = [f"  // {_GENERATED_NOTE}"]
    for value in values:
        lines.append(f'  "{value}",')
    return "\n".join(lines)


def _marker_pattern(comment_prefix: str) -> re.Pattern[str]:
    """Match a marker block, capturing the body between the two markers.

    The prefix differs per language (`#` vs `//`) but the marker text does not,
    so a drifted mirror is greppable by the same string in either file.
    """
    return re.compile(
        rf"(^[ \t]*{re.escape(comment_prefix)} {re.escape(BEGIN)}[ \t]*\n)"
        rf"(.*?)"
        rf"(^[ \t]*{re.escape(comment_prefix)} {re.escape(END)}[ \t]*$)",
        re.DOTALL | re.MULTILINE,
    )


def splice(source: str, comment_prefix: str, body: str, path: Path) -> str:
    pattern = _marker_pattern(comment_prefix)
    match = pattern.search(source)
    if match is None:
        raise DriftError(
            f"{path.relative_to(REPO_ROOT)} is missing its generated-section markers.\n"
            f"  Expected a line containing: {comment_prefix} {BEGIN}\n"
            f"  and a later line containing: {comment_prefix} {END}\n"
            "Re-add them around the source_type enum; codegen refuses to guess where "
            "the boundary is rather than risk overwriting hand-written code."
        )
    return source[: match.start(2)] + body + "\n" + source[match.start(3) :]


# ---------------------------------------------------------------------------
# Field-name verification
# ---------------------------------------------------------------------------


def pydantic_fields(source: str) -> set[str]:
    body = source.split("class NormalizedRecord", 1)[-1]
    return set(re.findall(r"^    ([a-z_][a-z0-9_]*)\s*:", body, re.MULTILINE))


def zod_fields(source: str) -> set[str]:
    match = re.search(r"z\s*\.\s*object\(\{(.*?)\n  \}\)", source, re.DOTALL)
    if match is None:
        return set()
    return set(re.findall(r"^\s{4}([a-z_][a-z0-9_]*)\s*:", match.group(1), re.MULTILINE))


def check_fields(expected: set[str], actual: set[str], label: str) -> list[str]:
    problems = []
    for name in sorted(expected - actual):
        problems.append(f"{label}: missing field '{name}' declared in the canonical schema")
    for name in sorted(actual - expected):
        problems.append(f"{label}: declares field '{name}' that the canonical schema does not")
    return problems


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build_expected() -> dict[Path, str]:
    """Return {path: fully-rendered file content} for every mirror."""
    schema = load_schema()
    values = source_types(schema)
    return {
        PYDANTIC_PATH: splice(
            PYDANTIC_PATH.read_text(encoding="utf-8"), "#", render_pydantic_enum(values), PYDANTIC_PATH
        ),
        ZOD_PATH: splice(ZOD_PATH.read_text(encoding="utf-8"), "//", render_zod_enum(values), ZOD_PATH),
    }


def collect_problems() -> list[str]:
    """Every way the mirrors currently disagree with the canonical schema."""
    schema = load_schema()
    problems: list[str] = []

    for path, expected in build_expected().items():
        if path.read_text(encoding="utf-8") != expected:
            problems.append(
                f"{path.relative_to(REPO_ROOT)}: source_type enum is out of sync with "
                "packages/contracts/normalized-record.schema.json"
            )

    expected_fields = schema_properties(schema)
    problems += check_fields(
        expected_fields,
        pydantic_fields(PYDANTIC_PATH.read_text(encoding="utf-8")),
        str(PYDANTIC_PATH.relative_to(REPO_ROOT)),
    )
    problems += check_fields(
        expected_fields,
        zod_fields(ZOD_PATH.read_text(encoding="utf-8")),
        str(ZOD_PATH.relative_to(REPO_ROOT)),
    )
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="exit non-zero if any mirror has drifted")
    mode.add_argument("--write", action="store_true", help="regenerate the mirrors in place")
    args = parser.parse_args(argv)

    try:
        if args.write:
            changed = []
            for path, expected in build_expected().items():
                if path.read_text(encoding="utf-8") != expected:
                    path.write_text(expected, encoding="utf-8")
                    changed.append(path.relative_to(REPO_ROOT))

            # Field drift cannot be auto-fixed: the type expressions are
            # hand-written on purpose. Report it and fail rather than write a
            # partial fix and exit 0, which would read as "synced".
            field_problems = [p for p in collect_problems() if "field" in p]
            for problem in field_problems:
                print(f"[sync-contracts] {problem}", file=sys.stderr)

            if changed:
                for path in changed:
                    print(f"[sync-contracts] regenerated {path}")
            else:
                print("[sync-contracts] mirrors already in sync")

            if field_problems:
                print(
                    "[sync-contracts] field drift must be fixed by hand -- field type "
                    "expressions are language-specific and are not generated.",
                    file=sys.stderr,
                )
                return 1
            return 0

        problems = collect_problems()
        if problems:
            print("[sync-contracts] contract mirrors have drifted:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print(
                "\nRun `python3 scripts/sync_contracts.py --write` to regenerate the "
                "enum, or fix field drift by hand.",
                file=sys.stderr,
            )
            return 1

        print("[sync-contracts] all mirrors match packages/contracts/normalized-record.schema.json")
        return 0

    except (DriftError, KeyError) as exc:
        print(f"[sync-contracts] {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
