"""
Canonical source_type values for NormalizedRecord.

These values are the dispatch key across the entire pipeline — extractors set
them, the DB stores them, the reporter dispatches on them, and the UI filters
by them. Never use raw string literals; always import from here.

This file must stay in sync with both siblings:
  - packages/contracts/normalized-record.schema.json   (source of truth)
  - packages/contracts/sourceType.ts                   (TypeScript mirror)

Do not add a value here by hand. Add it to the canonical schema and run
`python3 scripts/sync_contracts.py --write`. CI runs --check and fails on drift.

Requires Python 3.12+. StrEnum members compare directly as strings without
.value, which removes a class of subtle bugs in dispatch code (renderer
registry lookups, source_type comparisons in analysis, etc.).

TypeScript equivalent: packages/contracts/sourceType.ts
"""
from enum import StrEnum


class SourceType(StrEnum):
    # SOURCE_TYPE GENERATED FROM packages/contracts/normalized-record.schema.json
    # generated by scripts/sync_contracts.py -- do not edit by hand
    CRASH_REPORT        = "crash_report"
    SIRI_FEEDBACK       = "siri_feedback"
    SFA_ANALYTICS       = "sfa_analytics"
    XP_AMP_TELEMETRY    = "xp_amp_telemetry"
    SAFARI_HISTORY      = "safari_history"
    SMS_ATTACHMENT      = "sms_attachment"
    NETWORK_USAGE       = "network_usage"
    GCLOUD_LOG          = "gcloud_log"
    SYSLOG_LINE         = "syslog_line"
    MVT_IOC_DETECTION   = "mvt_ioc_detection"
    TIMESTAMP_ANOMALY   = "timestamp_anomaly"
    ILEAPP_RECORD       = "ileapp_record"
    LLM_FLAGGED_ANOMALY = "llm_flagged_anomaly"
    # END SOURCE_TYPE


def is_source_type(value: str) -> bool:
    """Return True if value is a registered SourceType string."""
    return value in SourceType._value2member_map_
